version: "3"

services:
  telegramagent:
    container_name: telegramagent
    hostname: telegramagent
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./telegramagent/Dockerfile
    volumes:
      - ./telegramagent/src:/app
    networks:
      - langflow_network

  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - LANGFLOW_CONFIG_DIR=app/langflow
    volumes:
      - langflow-data:/app/langflow

    networks:
      - langflow_network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
    networks:
      - langflow_network

volumes:
  langflow-postgres:
  langflow-data:


networks:
  langflow_network:
    driver: bridge